version: '3.8'

services:

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duc2962001
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"